[names]
pink                 = "oklch(0.86774 0.07354 7.0855)"
lightpink            = "oklch(0.84739 0.08579 9.0865)"
snow                 = "oklch(0.98894 0.00534 17.247)"
rosybrown            = "oklch(0.69274 0.0548 18.565)"
crimson              = "oklch(0.57119 0.22194 20.087)"
lightcoral           = "oklch(0.72464 0.13774 21.029)"
indianred            = "oklch(0.61544 0.14415 22.228)"
mistyrose            = "oklch(0.94001 0.03008 25.281)"
brown                = "oklch(0.48061 0.15966 25.562)"
firebrick            = "oklch(0.49677 0.17969 26.815)"
salmon               = "oklch(0.735 0.15151 28.06)"
maroon               = "oklch(0.37669 0.15458 29.234)"
darkred              = "oklch(0.39986 0.16408 29.234)"
red                  = "oklch(0.62796 0.25768 29.234)"
tomato               = "oklch(0.69622 0.19552 32.321)"
orangered            = "oklch(0.6602 0.22936 35.403)"
darksalmon           = "oklch(0.75074 0.10818 39.394)"
coral                = "oklch(0.73511 0.16799 40.247)"
lightsalmon          = "oklch(0.79376 0.12483 42.425)"
sienna               = "oklch(0.52648 0.11512 44.604)"
chocolate            = "oklch(0.6344 0.15499 50.266)"
saddlebrown          = "oklch(0.47078 0.11214 50.845)"
seashell             = "oklch(0.97602 0.01425 57.592)"
darkorange           = "oklch(0.75054 0.17911 58.283)"
sandybrown           = "oklch(0.784 0.12691 59.71)"
peru                 = "oklch(0.67819 0.12275 62.182)"
peachpuff            = "oklch(0.91125 0.06 63.699)"
linen                = "oklch(0.96024 0.01715 67.622)"
orange               = "oklch(0.79269 0.17103 70.67)"
bisque               = "oklch(0.93286 0.05145 71.849)"
burlywood            = "oklch(0.80454 0.07786 73.417)"
tan                  = "oklch(0.78619 0.06382 74.619)"
antiquewhite         = "oklch(0.94669 0.03108 75.219)"
navajowhite          = "oklch(0.9164 0.07301 77.436)"
blanchedalmond       = "oklch(0.94844 0.04493 78.06)"
papayawhip           = "oklch(0.95808 0.03826 80.032)"
moccasin             = "oklch(0.92962 0.06754 81.379)"
darkgoldenrod        = "oklch(0.65207 0.1322 81.572)"
wheat                = "oklch(0.90883 0.0615 83.033)"
oldlace              = "oklch(0.97234 0.02156 83.264)"
goldenrod            = "oklch(0.75157 0.14693 83.988)"
floralwhite          = "oklch(0.98623 0.01422 84.583)"
gold                 = "oklch(0.88677 0.18219 95.33)"
cornsilk             = "oklch(0.9773 0.03726 95.439)"
lemonchiffon         = "oklch(0.97781 0.05822 102.16)"
khaki                = "oklch(0.91349 0.11192 102.83)"
palegoldenrod        = "oklch(0.92105 0.07981 103.18)"
darkkhaki            = "oklch(0.76747 0.09804 104.51)"
ivory                = "oklch(0.99598 0.01962 106.75)"
beige                = "oklch(0.96357 0.03278 107)"
lightyellow          = "oklch(0.99201 0.04024 107.11)"
lightgoldenrodyellow = "oklch(0.97501 0.05184 107.32)"
olive                = "oklch(0.58066 0.12658 109.77)"
yellow               = "oklch(0.96798 0.21101 109.77)"
darkolivegreen       = "oklch(0.49552 0.0896 126.19)"
olivedrab            = "oklch(0.59948 0.13738 126.32)"
yellowgreen          = "oklch(0.78485 0.18374 126.64)"
greenyellow          = "oklch(0.91305 0.23346 130.02)"
chartreuse           = "oklch(0.89026 0.2648 136.01)"
lawngreen            = "oklch(0.88175 0.26307 136.17)"
darkgreen            = "oklch(0.43602 0.14837 142.5)"
green                = "oklch(0.51975 0.17686 142.5)"
lime                 = "oklch(0.86644 0.29483 142.5)"
limegreen            = "oklch(0.74187 0.22865 142.83)"
forestgreen          = "oklch(0.5578 0.16878 142.89)"
palegreen            = "oklch(0.90354 0.16242 144.09)"
lightgreen           = "oklch(0.868 0.1558 144.09)"
darkseagreen         = "oklch(0.75086 0.07971 144.73)"
honeydew             = "oklch(0.98484 0.02521 145.38)"
springgreen          = "oklch(0.87493 0.23526 151.02)"
seagreen             = "oklch(0.56853 0.11871 154.95)"
mediumseagreen       = "oklch(0.68404 0.14402 155)"
mediumspringgreen    = "oklch(0.86681 0.20674 156.9)"
mintcream            = "oklch(0.99117 0.01237 164.81)"
mediumaquamarine     = "oklch(0.77669 0.10985 168.82)"
aquamarine           = "oklch(0.91499 0.13039 168.99)"
turquoise            = "oklch(0.82233 0.13074 185.09)"
lightseagreen        = "oklch(0.6912 0.11421 188.96)"
mediumturquoise      = "oklch(0.7868 0.11622 191.56)"
darkcyan             = "oklch(0.57652 0.09841 194.77)"
teal                 = "oklch(0.54312 0.09271 194.77)"
aqua                 = "oklch(0.9054 0.15455 194.77)"
cyan                 = "oklch(0.9054 0.15455 194.77)"
darkslategray        = "oklch(0.40296 0.03772 195.76)"
darkslategrey        = "oklch(0.40296 0.03772 195.76)"
paleturquoise        = "oklch(0.90691 0.06323 196.09)"
lightcyan            = "oklch(0.97786 0.03203 196.64)"
darkturquoise        = "oklch(0.77193 0.13144 196.64)"
azure                = "oklch(0.98895 0.01572 196.9)"
cadetblue            = "oklch(0.65768 0.06501 198.3)"
powderblue           = "oklch(0.87508 0.0502 205.73)"
lightblue            = "oklch(0.85623 0.04894 219.65)"
skyblue              = "oklch(0.81482 0.08192 225.75)"
deepskyblue          = "oklch(0.75535 0.15342 231.64)"
lightskyblue         = "oklch(0.82062 0.09453 236.75)"
aliceblue            = "oklch(0.97514 0.01266 244.25)"
steelblue            = "oklch(0.588 0.09934 245.74)"
slategray            = "oklch(0.5925 0.03092 248.35)"
slategrey            = "oklch(0.5925 0.03092 248.35)"
lightslategray       = "oklch(0.61902 0.0325 248.35)"
lightslategrey       = "oklch(0.61902 0.0325 248.35)"
dodgerblue           = "oklch(0.65201 0.19012 253.21)"
lightsteelblue       = "oklch(0.81362 0.04281 255.03)"
cornflowerblue       = "oklch(0.67462 0.14136 261.34)"
blue                 = "oklch(0.45201 0.31321 264.05)"
darkblue             = "oklch(0.28782 0.19944 264.05)"
mediumblue           = "oklch(0.38345 0.26571 264.05)"
navy                 = "oklch(0.27115 0.18789 264.05)"
royalblue            = "oklch(0.55985 0.18823 266.4)"
midnightblue         = "oklch(0.28812 0.14363 272.76)"
mediumslateblue      = "oklch(0.60447 0.19389 285.5)"
slateblue            = "oklch(0.54357 0.17123 285.54)"
lavender             = "oklch(0.9309 0.02694 285.86)"
darkslateblue        = "oklch(0.41434 0.12484 286.04)"
ghostwhite           = "oklch(0.98112 0.00927 286.23)"
mediumpurple         = "oklch(0.62518 0.15415 297.27)"
blueviolet           = "oklch(0.53376 0.25031 301.37)"
indigo               = "oklch(0.33898 0.17927 301.68)"
rebeccapurple        = "oklch(0.44027 0.1603 303.37)"
darkviolet           = "oklch(0.51491 0.26067 309.81)"
darkorchid           = "oklch(0.54111 0.22724 311.51)"
mediumorchid         = "oklch(0.62558 0.20244 319.23)"
thistle              = "oklch(0.83329 0.04391 325.96)"
plum                 = "oklch(0.78328 0.10776 326.54)"
violet               = "oklch(0.7619 0.18612 327.21)"
fuchsia              = "oklch(0.70167 0.32249 328.36)"
magenta              = "oklch(0.70167 0.32249 328.36)"
darkmagenta          = "oklch(0.4468 0.20535 328.36)"
purple               = "oklch(0.42091 0.19345 328.36)"
orchid               = "oklch(0.70213 0.18126 328.71)"
mediumvioletred      = "oklch(0.55337 0.22165 349.69)"
hotpink              = "oklch(0.7283 0.19708 351.99)"
lavenderblush        = "oklch(0.96833 0.01741 355.1)"
deeppink             = "oklch(0.65493 0.26134 356.94)"
palevioletred        = "oklch(0.67397 0.135 359.97)"
black                = "oklch(0 0 0)"
darkgray             = "oklch(0.73481 0 0)"
darkgrey             = "oklch(0.73481 0 0)"
dimgray              = "oklch(0.52081 0 0)"
dimgrey              = "oklch(0.52081 0 0)"
gainsboro            = "oklch(0.89449 0 0)"
gray                 = "oklch(0.59987 0 0)"
grey                 = "oklch(0.59987 0 0)"
lightgray            = "oklch(0.86686 0 0)"
lightgrey            = "oklch(0.86686 0 0)"
silver               = "oklch(0.8078 0 0)"
white                = "oklch(1 0 0)"
whitesmoke           = "oklch(0.97015 0 0)"
transparent          = "oklch(0 0 0 / 0)"
